import React, { useState } from "react";
import Head from "next/head";
import style from "../public/css/list.module.scss";
import axios from "axios";
export default function LoginScreen() {
  const [id, setId] = useState("");
  const [name, setName] = useState("");
  const [wage, setWage] = useState("");

  function submitForm() {
    axios
      .post(
        "/api/v1/employee",
        {
          id: id,
          name: name,
          wage: wage,
        },
        {
          headers: {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
          },
        }
      )
      .then(({ data }) => {
        window.location.href = "/list";
      });
  }
  function onChangeId(e) {
    setId(e);
  }
  function onChangeName(e) {
    setName(e);
  }
  function onChangeWage(e) {
    setWage(e);
  }
  return (
    <div>
      <Head>
        <title>List Employee</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={style.flex}>
        ID:
        <input onChange={onChangeId} />
      </div>
      <div className={style.flex}>
        Name:
        <input onChange={onChangeName} />
      </div>
      <div className={style.flex}>
        Wage:
        <input onChange={onChangeWage} />
      </div>
      <button onClick={(e) => submitForm(e)}>Submit</button>
    </div>
  );
}
