import React, { useEffect, useState } from "react";
import Head from "next/head";
import style from "../public/css/list.module.scss";
import axios from "axios";
export default function LoginScreen() {
  const [listEmployee, setListEmployee] = useState("");
  useEffect(() => {
    axios.get("/api/v1/employee").then(({ data }) => {
      data.success ? setListEmployee(data) : "";
    });
  }, []);
  return (
    <div>
      <Head>
        <title>List Employee</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {listEmployee?.map((value, key) => (
        <div key={key} className={style.flex}>
          <p>{value.id}</p>
          <p>{value.name}</p>
          <p>{value.wage}</p>
        </div>
      ))}
    </div>
  );
}
